# Generated by Django 2.1.3 on 2018-11-29 20:11

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='page name in arabic')),
                ('name_en', models.CharField(max_length=100, verbose_name='page name in english')),
                ('description_ar', models.TextField(max_length=1000, verbose_name='page description in arabic')),
                ('description_en', models.TextField(max_length=1000, verbose_name='page description in english')),
                ('click_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='times of click')),
                ('detail_ar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='page details in arabic')),
                ('detail_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='page details in english')),
                ('address_ar', ckeditor.fields.RichTextField(help_text='<span class="red-text">Note:- Address will appears in Contact Us page only </span>', verbose_name='address in arabic')),
                ('address_en', ckeditor.fields.RichTextField(help_text='<span class="red-text">Note:- Address will appears in Contact Us page only </span>', verbose_name='address in english')),
                ('phones', ckeditor.fields.RichTextField(help_text='<span class="red-text">Note:- Phones will appears in Contact Us page only </span>', verbose_name='phones')),
                ('websites', ckeditor.fields.RichTextField(help_text='<span class="red-text">Note:- Emails and website will appears in Contact Us page only </span>', verbose_name='emails and website')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
