# Generated by Django 2.1.3 on 2018-11-29 23:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('subject', models.CharField(max_length=100, verbose_name='message subject')),
                ('body', models.TextField(blank=True, max_length=1000, verbose_name='message body')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='address_ar',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<span style="color:red; font-size:14px;">Note:- Address will appears in Contact Us page only </span>', verbose_name='address in arabic'),
        ),
        migrations.AlterField(
            model_name='page',
            name='address_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<span style="color:red; font-size:14px;">Note:- Address will appears in Contact Us page only </span>', verbose_name='address in english'),
        ),
        migrations.AlterField(
            model_name='page',
            name='phones',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<span style="color:red; font-size:14px;">Note:- Phones will appears in Contact Us page only </span>', verbose_name='phones'),
        ),
        migrations.AlterField(
            model_name='page',
            name='websites',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<span style="color:red; font-size:14px;">Note:- Emails and website will appears in Contact Us page only </span>', verbose_name='emails and website'),
        ),
    ]
