# Generated by Django 2.1.3 on 2018-11-30 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181130_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone must be in correct form', regex='^(00|[+]|0)[0-9]+$')], verbose_name='Phone Number'),
        ),
    ]
