# Generated by Django 2.1.3 on 2018-11-26 22:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(help_text='Product Name in Arabic', max_length=50, verbose_name='name in arabic ')),
                ('name_en', models.CharField(blank=True, help_text='Product Name in English', max_length=50, verbose_name='name in english')),
                ('description_ar', models.TextField(help_text='Product Description in Arabic', max_length=200, verbose_name='description in arabic')),
                ('description_en', models.TextField(blank=True, help_text='Product Description in English', max_length=200, verbose_name='description in english')),
                ('detail_ar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Product Detail in Arabic', verbose_name='detail in arabic')),
                ('detail_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Product Detail in English', verbose_name='detail in english')),
                ('material_ar', models.CharField(blank=True, help_text='Material in Arabic', max_length=50, verbose_name='material in arabic')),
                ('material_en', models.CharField(blank=True, help_text='Material in English', max_length=50, verbose_name='material in english')),
                ('keywords_ar', models.TextField(blank=True, help_text='Product keywords in Arabic', max_length=1000, verbose_name='keywords in arabic')),
                ('keywords_en', models.TextField(blank=True, help_text='Product keywords in English', max_length=1000, verbose_name='keywords in english')),
                ('length', models.FloatField(blank=True, help_text='Product Length', null=True, verbose_name='length')),
                ('width', models.FloatField(blank=True, help_text='Product Width', null=True, verbose_name='width')),
                ('height', models.FloatField(blank=True, help_text='Product Height', null=True, verbose_name='height')),
                ('weight', models.FloatField(blank=True, help_text='Product Weight', null=True, verbose_name='weight')),
                ('thickness', models.FloatField(blank=True, help_text='Product Thickness', null=True, verbose_name='thickness')),
                ('density', models.FloatField(blank=True, help_text='Product Density', null=True, verbose_name='density')),
                ('ref', models.CharField(blank=True, help_text='Product Code', max_length=50, verbose_name='product code')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/building')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='category in arabic')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='category in english')),
                ('description_ar', models.TextField(blank=True, max_length=1000, verbose_name='description in arabic')),
                ('description_en', models.TextField(blank=True, max_length=1000, verbose_name='description in english')),
            ],
            options={
                'verbose_name': 'Product Main Category',
                'verbose_name_plural': 'Products Main Category',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='sub category in arabic')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='sub category in english')),
                ('description_ar', models.TextField(blank=True, max_length=1000, verbose_name='description in arabic')),
                ('description_en', models.TextField(blank=True, max_length=1000, verbose_name='description in english')),
                ('main_category', models.ForeignKey(blank=True, help_text='Choose Product Category Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductMainCategory', verbose_name='main category name')),
            ],
            options={
                'verbose_name': 'Product Sub Category',
                'verbose_name_plural': 'Products Sub Category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose Product Category Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubCategory', verbose_name='category name'),
        ),
    ]
