# Generated by Django 2.1.3 on 2018-11-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181127_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='times of click'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='click_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='times of click'),
        ),
    ]
