# Generated by Django 2.1.3 on 2018-11-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181128_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, help_text='Product Density', max_length=50, null=True, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, help_text='Product Height', max_length=50, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, help_text='Product Length', max_length=50, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, help_text='Product Thickness', max_length=50, null=True, verbose_name='thickness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Product Weight', max_length=50, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, help_text='Product Width', max_length=50, null=True, verbose_name='width'),
        ),
    ]
