# Generated by Django 2.1.3 on 2018-11-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181128_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(help_text='Product Description in English', max_length=1000, verbose_name='description in english'),
        ),
    ]
