# Generated by Django 2.1.3 on 2018-11-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181128_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='times of click'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='click_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='times of click'),
        ),
    ]
