# Generated by Django 2.1.3 on 2018-11-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181129_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose Subcategory Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubCategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text='Choose Main Category Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductMainCategory', verbose_name='main category name'),
        ),
    ]
