# Generated by Django 2.1.3 on 2018-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181130_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_home',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', help_text='Show the Prdouct in homepage', max_length=1, verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='show_footer',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', help_text='Show Subcategory in footer', max_length=1, verbose_name='Show in footer'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='show_home',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', help_text='Show Subcategory in homepage', max_length=1, verbose_name='Show in home'),
        ),
    ]
